### PR TITLE
New option for electrode plotting: cfg.edgeBlack, AND new input option for cfg.edgeBlack

### PR DESCRIPTION
**Pull request by stebick**
2 changes:

1) I added a new input option for cfg.edgeBlack. You can now define a cell array with electrodew labels which define which specific electrodes should have a black edge. 

2) A new option cfg.edgeColors:  a nx2 cell array for electrode label - color combinations for edges.  Electrodes not mentioned will have a black edge.

### CODE REVIEW

**Comment by pierremegevand** [comment]
Hi Steph and David,

I just wanted to let you know I had implemented the same function in the
iELVis_pm branch of the main repo (
https://github.com/iELVis/iELVis/tree/iELVis_pm) a few months back.

Another thing I have implemented, which I think could be useful for
everyone, is the option to pass any colormap to the electrode plotting
functions via the new cfg.elecCmapName. Check it out!

All the best,

Pierre
--
Pierre Mégevand <http://twitter.com/pierre_vanmedge>
http://twitter.com/pierre_vanmedge

**Comment by stebick** [comment]
Hi Pierre, 

 

Oh, sorry,  I didn’t see that! Was this merged to the master branch? We can revert my change if it has. Or, even if it hasn’t we can revert mine and ad yours. 

 

Best, 

Stephan

**Comment by pierremegevand** [comment]
I didn't merge it myself, because the last time I tried to merge a branch
of mine with the main branch, I introduced unwanted mistakes (that was a
while ago). That said, I've been using the elecColorsEdge and elecCmapName
options for many figures over the past few months, and I haven't seen any
unwanted behavior, so I suppose we could simply merge everything together?
--
Pierre Mégevand <http://twitter.com/pierre_vanmedge>
http://twitter.com/pierre_vanmedge

**Comment by stebick** [comment]
Sounds good to me!

I think your elecColorsEdge  takes an RGB matrix as input, while cfg.edgeColors takes a cell array with electrode label and color combination. So, both might be useful. 

 

I’m not sure if merging your change into the current master will cause problems, what do you think David? If so, feel free to revert my contribution and I’ll add it again after Pierre added his. 

 

Best, 

Stephan

**Comment by dmgroppe** [comment]
I would love to merge Pierre's branch with Master. However, when I looked
into this months ago, it was not trivial and I simply didn't have the time
to take resolve the conflicts in the code.


If you do try to merge them, run the test scripts in
https://github.com/iELVis/iELVis/tree/master/iELVis_MAIN/TEST_SCRIPTS
to make sure things still work.

**Pull request merged**
